### PR TITLE
Added gateway#purchase

### PR DESCRIPTION
**Pull request by abhishekgupta5**
**Issue:** https://linear.app/nebulab-retainers/issue/ABU-11/implement-soliduspaytomorrowgatewaypurchase

- [x] QAed

### CODE REVIEW

**Comment by DanielePalombo** [comment]
#14 is not merged yet, so this PR should be brought back to draft, to avoid being merged.

**Comment by abhishekgupta5** [comment]
> #14 is not merged yet, so this PR should be brought back to draft, to avoid being merged.

#14 is merged hence moving this to ready for review

**Comment by DanielePalombo** [comment]
Only PR opened on the main branch should be `Ready for review`

**Comment by DanielePalombo** [comment]
Why it's based on the ABU-12 branch?

**Comment by abhishekgupta5** [comment]
> Why it's based on the ABU-12 branch?

Earlier, this was rebased on abu-12 branch that's why made that the base for easier review.
Changed to master now

**Comment by DanielePalombo** [comment]
Is it ready for review now?

**Comment by abhishekgupta5** [comment]
> Is it ready for review now?

yes

**Review by DanielePalombo — APPROVED** [review]
LGTM

**Pull request merged**
